apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-certificate
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: {{ .Values.certManager.issuer }}
  dnsNames:
    - {{ index .Values.ingress.hosts .Values.environment }}

